### ISSUE TITLE
Importing the root entry makes Vite copy every file in schema/ into the consumer build (146 kB, unreferenced)

### ISSUE THREAD

**Issue by astrapi69** [astrapi69/learn-content-engine#203]
## Finding

`src/validate.ts` builds the schema path from a template. See engine `main` at cadea353, `src/validate.ts:41-44`, and the published 0.29.0 `dist/validate.js:32` (tarball shasum fd605429a495b56bdaaf147c814a93fcfeff0a41):

```ts
const loadSchema = (fileName: string): object =>
  JSON.parse(
    readFileSync(fileURLToPath(new URL(`../schema/${fileName}`, import.meta.url)), "utf8"),
  ) as object;
```

Vite turns a `new URL(...)` built from a template literal into a lookup over every file that matches `../schema/*`. In the built JS the call becomes:

```js
new URL(Object.assign({
  "../schema/content-manifest.schema.json": ...,
  "../schema/grading-presets.json": ...,
  "../schema/lesson.schema.json": ...,
  "../schema/quality-rules.json": ...
})[...], ...)
```

So Vite copies every file in `schema/`, including `grading-presets.json`, which `validate.ts` never reads. The 354-byte `quality-rules.json` is below Vite's default `assetsInlineLimit`, so Vite inlines it as a data URL instead of copying it.

The root entry re-exports `validateLesson` / `validateManifest` (`src/index.ts:25`), so `validate.js` is in the module graph of every root import. Vite copies the files when it transforms the module, even if tree-shaking removes the code later.

Measured 2026-09-24 with a minimal Vite project: vite 8.3.0 (the app's version, rolldown 1.2.10), default config, `vite build`, learn-content-engine 0.29.0 from npm. `main.js` holds exactly one import:

| `main.js` imports | JS emitted (bytes) | JSON files emitted (bytes) |
|---|---|---|
| `import { parseLesson } from "learn-content-engine"` | 30,482 | lesson.schema 55,033 + content-manifest.schema 21,692 + grading-presets 69,488 = 146,213 |
| `import "learn-content-engine"` (nothing used) | 685 | the same three, 146,213 |
| `import { validateLesson } from "learn-content-engine"` | 149,141 | the same three, 146,213 |
| `import { validateLessonRules } from "learn-content-engine/rules"` | 17,414 | none |

- In the two builds that do not call `validateLesson`, no emitted JS names any of the three files. They are copied but nothing references them.
- Every root build logs `Module "node:fs" has been externalized for browser compatibility, imported by .../learn-content-engine/dist/validate.js`, and the same for `node:url`.
- Even when the code references them, the browser build cannot read the files. We ran the `validateLesson` build with a minimal DOM stub, and it throws `TypeError: (0 , kr.fileURLToPath) is not a function` because Vite replaces `node:url` / `node:fs` with empty stubs. This matches the documented limit in `docs/validation.md:138-139`: it reads the schema from the file system, which a browser does not have.

In the app (adaptive-learner):

- `frontend/src/lib/content/engine/index.ts:37-45` (develop 437ecbf1) imports parse functions from the root entry and no validator.
- The local production build on the current pin 0.26.0 (`frontend/dist`, version.json 2.15.0, built 2026-09-23) contains `assets/lesson.schema-BlBsi9ET.json` (55,059 bytes) and `assets/content-manifest.schema-DAG8Hlp0.json` (17,197 bytes). `grep -rl` finds neither name anywhere in `dist` (exit 1), and `sw.js` does not precache them (Workbox `globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"]`, `frontend/vite.config.ts:133`).
- A production build log with the 0.29.0 pin (the re-pin in adaptive-learner#3238, built in a scratch directory on 2026-09-24 and not re-run for this issue) lists a third file, `grading-presets-D7AAHFVB.json` at 69.48 kB. It has the same content hash as in the minimal reproduction above.

### What this means for the /rules bundle figure

The figures from #191 / #192 (esbuild: `/rules` 21,590 bytes minified vs. 144,637 bytes for `validateLesson`) are repeated in `CHANGELOG.md:54-55`, `docs/validation.md:136-139` and `docs/architecture.md:375`. They count JS bytes only.

- For the `/rules` entry the figures hold. Under Vite it emits 17,414 bytes of JS and no extra files, because `rules.ts` does not reach `validate.ts` (see its imports in `src/rules.ts:20-27` and the boundary test from #192).
- The root entry is different. Every root import adds 146,213 bytes of JSON files to the build, including the parse-only imports the app uses. The JS figure does not show this.
- A consumer that switches its validation to `/rules` but still imports `parseLesson` and the other parse functions from the root entry still gets the files.

## Why it matters

- Every browser consumer of the root entry ships 146 kB (0.29.0) of JSON that its code never loads. Any new file in `schema/` is added automatically. `grading-presets.json` was added this way in 0.29.0, and nothing in the engine reads it.
- The app does not download these files today, because nothing references them and the service worker does not precache them. So the cost is deploy size and build noise, not user traffic. A PWA whose precache pattern includes `*.json` would push the files to every client. That is why this is P3.
- Every consumer build that imports the root entry prints the `node:fs` / `node:url` warnings, even if it never validates.
- The `/rules` figure is correct, but it reads like the whole browser cost. For a consumer that also uses the root entry, it is not.

## Proposed direction

Goal: a file ends up in a consumer build only if code the consumer uses reads it.

1. Recommended: load the two schemas as JSON modules instead of reading them from disk, so the bundler treats them like code. Two ways:
   - `import lessonSchema from "../schema/lesson.schema.json" with { type: "json" };`, and the same for the manifest schema.
   - A generated module, e.g. `src/schemas.generated.ts` exporting both objects, kept in sync with `schema/` by a drift check. `make sync-types` / `sync-types-check` (`Makefile:51,54`) already do this for the lesson types.

   Effects:
   - With `sideEffects: false` (`package.json:47`), a consumer that never calls `validateLesson` / `validateManifest` gets neither schema and no copied file.
   - No runtime code references `grading-presets.json` or `quality-rules.json` any more.
   - `validate.ts` no longer imports `node:fs` / `node:url`, so the warnings go away and `validateLesson` becomes usable in a browser. Its JS then includes the schemas (76,725 bytes as files, less once whitespace is stripped).

   To check before choosing: whether import attributes and JSON modules work on the `engines` floor (`node >=18`), and whether the CLI (`src/cli.ts:40` calls `validateLesson`) would print an ExperimentalWarning there. The generated module avoids both, but the package then carries each schema twice.
2. Not enough on its own: one literal URL per file (`new URL("../schema/lesson.schema.json", import.meta.url)`). This ends the `schema/*` lookup, so `grading-presets.json` and `quality-rules.json` are no longer copied. But the reproduction shows Vite copies files even when tree-shaking drops the code. So Vite would still copy the two schemas into every build that imports the root entry, and `validateLesson` would still not run in a browser. This is inferred and not measured for this form (see First step).
3. Opt-in loading: move the structural layer behind its own subpath (e.g. `learn-content-engine/validate`) or a factory that takes the schemas as arguments. This keeps the root entry free of file access, but it breaks every consumer that imports `validateLesson` from the root entry and needs a deprecation path. Use it only if option 1 fails on the Node floor.

Docs (per `.claude/rules/release.md`): add the emitted-files view next to the JS bundle figures in `docs/validation.md:136-139` and `docs/architecture.md:375`. With option 1, the statement that `validateLesson` reads the schema from the file system also changes.

## Tests (TDD)

1. RED reproduction:
   - In `src/browser-import.test.ts`, mock `node:fs` to throw (as the engine#59 test does). Then *calling* `validateLesson({})` must return `{ valid: false, ... }` instead of throwing. This fails today, because the call reaches `readFileSync`.
   - Add a module-graph check next to the `/rules` boundary test from #192: no module reachable from `src/index.ts` contains `new URL(` with `import.meta.url` or imports `node:fs` / `node:url`. This fails today on `validate.ts`. Add seeded negatives for a template URL and for a literal URL.
2. Happy path: `validateLesson` / `validateManifest` return identical results on every conformance fixture before and after (existing parity tests), and CLI `lint` still validates under Node.
3. Edge: no runtime module references `schema/grading-presets.json` or `schema/quality-rules.json`. A bare `import "learn-content-engine"` still does nothing at import time (the existing engine#59 test stays green).
4. Boundary:
   - The packed tarball (`npm pack`) loads the schemas via `dist/validate.js` on the lowest Node version `engines` allows. If the floor has to move for import attributes, raise `engines` in the same PR.
   - If you choose the generated module, the drift check fails when `schema/lesson.schema.json` changes without a regeneration.

Record in the PR the four-variant Vite table above, before and after.

## First step

The claim in option 2 (literal URLs still copy the two schemas) and the costs of option 1 are inferred, not measured. Before implementing:

1. In a scratch Vite 8.3.0 project, patch `node_modules/learn-content-engine/dist/validate.js` two ways: (a) literal URLs, (b) JSON imports.
2. Rebuild the four variants and record the emitted files.
3. Run the CLI with (b) on the lowest Node version in `engines`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
